### ISSUE TITLE
Entangler map in the generator is wrong for the case n!=2

### ISSUE THREAD

**Issue by mrnp95** [QuBiTUCLA/RP-QST#5]
The implemented entangler map is just for two-qubit generators:

https://github.com/QuBiTUCLA/RP-QST/blob/427665102ca3cdb1304f8123432adc8ad4d4865a/rp_qst_src/__init__.py#L173

@josiahjchang @fracho123  Looking at the QGAN paper or the tutorials that I gave you, you can fix it. It's not supposed to be just between qubits 0 and 1.

**Comment by fracho123** [comment]
We fixed it in the latest pull request.
